# Generated by Django 6.0.7 on 2026-07-18 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('specialization', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=256)),
                ('my_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.doctor')),
            ],
        ),
    ]
